module.exports = {
  'GET /dashboard/author': ['author'],
  'GET /dashboard/reviewer': ['reviewer'],
  'GET /dashboard/editor': ['editor'],
  'GET /dashboard/attendee': ['attendee'],
  'GET /submissions/new': ['author'],
  'POST /submissions': ['author'],
  'GET /submissions/replace': ['author'],
  'POST /submissions/replace': ['author'],
  'GET /submissions/drafts': ['author'],
  'POST /submissions/drafts/save': ['author'],
  'POST /submissions/drafts/resume': ['author'],
  'POST /submissions/drafts/submit': ['author'],
  'GET /reviews/assign': ['editor'],
  'POST /reviews/assign': ['editor'],
  'GET /reviews/invitation': ['reviewer'],
  'POST /reviews/invitation/respond': ['reviewer'],
  'GET /reviews/assignments': ['reviewer'],
  'GET /reviews/form': ['reviewer'],
  'POST /reviews/form': ['reviewer'],
  'POST /reviews/form/save': ['reviewer'],
  'POST /reviews/form/submit': ['reviewer'],
  'GET /editor/reviews': ['editor'],
  'POST /editor/reviews': ['editor'],
  'GET /editor/decision': ['editor'],
  'POST /editor/decision': ['editor'],
  'POST /notifications/author-decision': ['editor'],
  'GET /schedule/generate': ['editor'],
  'POST /schedule/generate': ['editor'],
  'GET /schedule/edit': ['editor'],
  'POST /schedule/edit': ['editor'],
  'GET /schedule/publish': ['editor'],
  'POST /schedule/publish': ['editor'],
  'GET /schedule/public': [],
  'GET /pricing': [],
  'GET /conference/register': ['author', 'reviewer', 'editor', 'attendee'],
  'POST /conference/register': ['author', 'reviewer', 'editor', 'attendee'],
  'GET /tickets/view': ['author', 'reviewer', 'editor', 'attendee'],
  'POST /tickets/view': ['author', 'reviewer', 'editor', 'attendee'],
  'POST /accounts/password': ['author', 'reviewer', 'editor', 'attendee'],
};
